CREATE  TABLE `SPECIMENINVENTORY`.`SURGERYTYPE_ASSOC` (
  `SURGERY_ID` INT NOT NULL ,
  `SURGERYTYPE` VARCHAR(45) NOT NULL ,
  INDEX `SURGERY_ID_IDX` (`SURGERY_ID` ASC) ,
  CONSTRAINT `SURGERY_FK`
    FOREIGN KEY (SURGERY_ID)
    REFERENCES `SPECIMENINVENTORY`.`SURGERY` (ID)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);
